### ISSUE TITLE
[ feature request ] recorder filename patterns

### ISSUE THREAD

**Issue by trws** [LLNL/Caliper#1]
As it stands, the recorder filename can either be auto-generated, or it can be a single static value.  It would be quite helpful to be able to specify a pattern from which to generate the name, or to be able to specify it through an API at runtime.

**Comment by daboehme** [comment]
Thanks Tom! I've actually ran into situations where that would be useful myself. It's on my TODO list.

**Comment by trws** [comment]
That's good to hear.  I ran into wanting it with flux, mainly because there are so many fork-points in the broker and runner components that profiling a run with four brokers can generate 20-30 caliper files, and which ones match which binaries is rather difficult to determine without some way to name them or searching through the actual data in the files to figure it out.
