### ISSUE TITLE
Possibly broken builds on regular systems

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#110]
@jarusified mentioned an attempted build on a regular system at school.

We should attempt to reproduce this, notably that even though we were building with the MPI compilers, we didn't detect the presence of MPI. If we can't reproduce this in three months, we should close this, but I'm worried our FindMPI is brittle

**Comment by daboehme** [comment]
In this spack build, CMake apparently doesn't find MPI correctly, even though the MPI compilers were specified on the cmake command line. This is the build output:

[build.txt](https://github.com/LLNL/Caliper/files/2051522/build.txt)

So far I was unable to reproduce this. Tried different systems, MPIs, and CMake versions in spack, but it always found and enabled MPI correctly.

**Comment by DavidPoliakoff** [comment]
Three months, closing
