### ISSUE TITLE
Unexpected query result when annotating code

### ISSUE THREAD

**Issue by deanchester** [LLNL/Caliper#142]
I have a halo exchange annotated like so: 

```
#ifdef INSTRUMENT
    CALI_MARK_BEGIN("CG_HALO_EXCHANGE"); 
#endif
    halo_update_driver(chunks, settings, settings->halo_depth);
#ifdef INSTRUMENT
    CALI_MARK_END("CG_HALO_EXCHANGE"); 
#endif
```

I was hoping to just query with the annotation to filter out my MPI function calls with a query like so: 
`cali-query -t -q "SELECT *  WHERE annotation=CG_HALO_EXCHANGE, NOT mpi.function" caliper-0.cali`

Yet these results seem to return quite a lot of profiled results:

> annotation       mpi.world.size time.duration mpi.rank time.inclusive.duration
> CG_HALO_EXCHANGE             28            53        0
> CG_HALO_EXCHANGE             28             5        0
> CG_HALO_EXCHANGE             28             2        0
> CG_HALO_EXCHANGE             28            14        0
> CG_HALO_EXCHANGE             28             1        0
> CG_HALO_EXCHANGE             28             1        0
> CG_HALO_EXCHANGE             28             5        0                     135
> CG_HALO_EXCHANGE             28            70        0
> CG_HALO_EXCHANGE             28             2        0
> CG_HALO_EXCHANGE             28             2        0
> CG_HALO_EXCHANGE             28            26        0
> CG_HALO_EXCHANGE             28             1        0
> CG_HALO_EXCHANGE             28             1        0
> CG_HALO_EXCHANGE             28             5        0                     665

When I perform a count I get numbers like so(query: "SELECT Count()  WHERE annotation=CG_HALO_EXCHANGE, NOT mpi.function"): 
> count
>  6764
>  6764
>  6764
>  3382

I was expecting to see 1 line saying 3382. I get the expected out when I set an MPI function I have captured: 

cali-query -t -q "SELECT Count()  WHERE annotation=CG_HALO_EXCHANGE, mpi.function=MPI_Isend" caliper-0.cali
count
 6764

Where this rank communicates with 2 other processes. 

My caliper configuration looks like: 

```
export CALI_SERVICES_ENABLE=trace,event,mpi,timestamp,recorder
export CALI_TIMER_SNAPSHOT_DURATION=true
export CALI_TIMER_INCLUSIVE_DURATION=true
export CALI_MPI_WHITELIST=all
export CALI_RECORDER_FILENAME=caliper-%mpi.rank%.cali
```

So what are the additional lines in the query without the MPI functions?

**Comment by daboehme** [comment]
Hi Dean,

Unfortunately, the Caliper data model and query system is a bit unintuitive in this case. (Long explanation: That query will also match trace records that mark the begin of MPI functions inside the CG_HALO_EXCHANGE region, where the "mpi.function" attribute isn't set yet. Hence all the extra output and "wrong" counts).

The solution in this case is to search only for records that mark the end of the annotation region. These have the "event.end#annotation" attribute, so you can write a query like so: 

`SELECT * WHERE event.end#annotation=CG_HALO_EXCHANGE`

This should also provide the correct counts.

Hope this helps!
-David

**Comment by deanchester** [comment]
Hi David,

Thanks for providing the insight! 

I am wanting to extract the time to pack and unpack some buffers away from the MPI calls. The `halo_update_driver` function looks something like: 

void halo_update_driver(double* sendBuf, double* recvBuf)
{
    pack(sendBuf); 
    MPI_ISend(sendBuf,....);
    MPI_IRecv(recvBuf,...); 
    MPI_WaitAll();
    unpack(recvBuf); 
}

Will this provide the total time which includes the MPI calls or just the time around the MPI calls? 

Many Thanks, 

Dean

**Comment by daboehme** [comment]
Hi Dean,

The annotation end records will only provide the inclusive time with the MPI functions. To get the exclusive time inside CG_HALO_EXCHANGE but outside of MPI, we'll have to aggregate all time.duration values outside of the MPI functions. This should do it:

`SELECT annotation,sum(time.duration) WHERE annotation=CG_HALO_EXCHANGE, NOT mpi.function GROUP BY annotation`

Note the `GROUP BY`. Also, this this will give you the total over the entire program/loop, not for each individual instance. 

If you group by both annotation and mpi.function, you can show both the MPI time and the exclusive time in CG_HALO_EXCHANGE. You can display this in a nice hierarchical fashion, too:

`cali-query -q "SELECT sum(time.duration) GROUP BY annotation,mpi.function WHERE annotation=CG_HALO_EXCHANGE FORMAT tree" caliper-0.cali`

The time shown for the CG_HALO_EXCHANGE region above the mpi functions in that output will be the exclusive time spent there, outside of MPI.

**Comment by deanchester** [comment]
That is the data that I have wanted! Many thanks for the help David! 

Kind Regards, 

Dean
