### ISSUE TITLE
CMake Process Stalls when unable to get to Internet

### ISSUE THREAD

**Issue by nmhamster** [LLNL/Caliper#149]
Caliper appears to download source code during configuration for build. This is very unhelpful for machines without internet connectivity. Can you provide a build system that doesn't require this (maybe with recursive or something?)?

**Comment by daboehme** [comment]
Caliper ships with its own copy of Gotcha since a48f5670b1c8c8f914ce132923bae424214005a4, and no longer attempts to download additional sources in the configure step by default.
