### ISSUE TITLE
MPI not saving to correct file

### ISSUE THREAD

**Issue by deanchester** [LLNL/Caliper#171]
Hi, 

I have an issue where caliper doesn't export to the correct filename. 

In my submission script I have: 

    export CALI_RECORDER_FILENAME=$PBS_O_WORKDIR/caliper/caliper-%mpi.rank%.cali

After the application has run all I have in caliper is 1 file called: "caliper-.cali"

I am running this on a Cray XC50 system. 

My submission script looks like: 

```
#!/bin/bash
#PBS -q arm
#PBS -l select=2
#PBS -l walltime=00:10:00


export OMP_NUM_THREADS=1

export LD_LIBRARY_PATH=$HOME/local/caliper/lib64:$LD_LIBRARY_PATH
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
cd $PBS_O_WORKDIR
mkdir "$PBS_O_WORKDIR/caliper"

export CALI_SERVICES_ENABLE=trace,event,mpi,timestamp,recorder
export CALI_TIMER_SNAPSHOT_DURATION=true
export CALI_TIMER_INCLUSIVE_DURATION=true
export CALI_MPI_WHITELIST=all
export CALI_RECORDER_FILENAME=$PBS_O_WORKDIR/caliper/caliper-%mpi.rank%.cali
#echo $CALI_RECORDER_FILENAME
aprun -n 56 ./tealeaf
```

In my stderr file I have lines that have been overwritten so I think this could be down to how the job is being run from aprun. 

Caliper was configured like so: 

`cmake -DCMAKE_INSTALL_PREFIX=$HOME/local/caliper/     -DCMAKE_C_COMPILER=/opt/cray/pe/craype/2.5.18/bin/cc     -DCMAKE_CXX_COMPILER=/opt/cray/pe/craype/2.5.18/bin/CC -DWITH_MPI=On -DMPI_C_COMPILER=/opt/cray/pe/craype/2.5.18/bin/cc -DWITH_TOOLS=On -DWITH_MPI=On -DWITH_GOTCHA=Off -DWITH_SAMPLER=On  ..
`

Any ideas what might be going on?

**Comment by daboehme** [comment]
Hi Dean,

It seems that the MPI service wasn't active. Did you link libcaliper-mpi.so in addition to libcaliper.so when building tealeaf?

**Comment by deanchester** [comment]
Yes I have the following flags for linking: 

    -L$(INSTRUMENT_CALIPER_LIB) -lcaliper -lcaliper-mpi -lcaliper-reader -lcaliper-common

**Comment by daboehme** [comment]
Ok, that looks good. Sometimes the linker throws out our MPI lib. You can try adding `cali_mpi_init()` somewhere in main() - that should pull it in.

```
#include <caliper/cali-mpi.h>

int main()
{
  // ...
  cali_mpi_init();
  // ...
}
```

**Comment by deanchester** [comment]
Adding that line results in the following error: 

> CC -O3 -march=native -funroll-loops -std=gnu99   -I/home/brx-dchester/local/caliper/include  obj/serial/shared.o  obj/serial/settings.o  obj/serial/profiler.o  obj/serial/parse_config.o  obj/serial/main.o  obj/serial/initialise.o  obj/serial/diffuse.o  obj/serial/comms.o  obj/serial/chunk.o  obj/serial/store_energy_driver.o  obj/serial/solve_finished_driver.o  obj/serial/set_chunk_state_driver.o  obj/serial/set_chunk_data_driver.o  obj/serial/remote_halo_driver.o  obj/serial/ppcg_driver.o  obj/serial/kernel_initialise_driver.o  obj/serial/jacobi_driver.o  obj/serial/halo_update_driver.o  obj/serial/field_summary_driver.o  obj/serial/eigenvalue_driver.o  obj/serial/cheby_driver.o  obj/serial/cg_driver.o  obj/serial/calculate_initial_residual_driver.o  obj/serial/store_energy.o  obj/serial/solver_methods.o  obj/serial/set_chunk_state.o  obj/serial/set_chunk_data.o  obj/serial/ppcg.o  obj/serial/pack_halos.o  obj/serial/local_halos.o  obj/serial/kernel_interface.o  obj/serial/kernel_initialise.o  obj/serial/jacobi.o  obj/serial/field_summary.o  obj/serial/cheby.o  obj/serial/cg.o -lm -lrt -lstdc++ -L/home/brx-dchester/local/caliper/lib64 -lcaliper -lcaliper-mpi -lcaliper-reader -lcaliper-common  -o tealeaf.serial
/usr/bin/ld: /home/brx-dchester/local/caliper/lib64/libcaliper-mpi.a(MpiReport.cpp.o): in function `(anonymous namespace)::MpiReport::write_output_cb(cali::Caliper*, cali::Channel*, cali::SnapshotRecord const*)':
MpiReport.cpp:(.text+0x1c4): undefined reference to `cali::aggregate_over_mpi(cali::CaliperMetadataDB&, cali::Aggregator&, int)'
collect2: error: ld returned 1 exit status

I have this included in the same file: 

    #include <caliper/cali.h>

**Comment by daboehme** [comment]
Ok, at least we are on the right track. Add `-lcaliper-mpi-common` to the list of libraries - that should fix it.

**Comment by deanchester** [comment]
This is the error now: 

> CC -O3 -march=native -funroll-loops -std=gnu99   -I/home/brx-dchester/local/caliper/include  obj/serial/shared.o  obj/serial/settings.o  obj/serial/profiler.o  obj/serial/parse_config.o  obj/serial/main.o  obj/serial/initialise.o  obj/serial/diffuse.o  obj/serial/comms.o  obj/serial/chunk.o  obj/serial/store_energy_driver.o  obj/serial/solve_finished_driver.o  obj/serial/set_chunk_state_driver.o  obj/serial/set_chunk_data_driver.o  obj/serial/remote_halo_driver.o  obj/serial/ppcg_driver.o  obj/serial/kernel_initialise_driver.o  obj/serial/jacobi_driver.o  obj/serial/halo_update_driver.o  obj/serial/field_summary_driver.o  obj/serial/eigenvalue_driver.o  obj/serial/cheby_driver.o  obj/serial/cg_driver.o  obj/serial/calculate_initial_residual_driver.o  obj/serial/store_energy.o  obj/serial/solver_methods.o  obj/serial/set_chunk_state.o  obj/serial/set_chunk_data.o  obj/serial/ppcg.o  obj/serial/pack_halos.o  obj/serial/local_halos.o  obj/serial/kernel_interface.o  obj/serial/kernel_initialise.o  obj/serial/jacobi.o  obj/serial/field_summary.o  obj/serial/cheby.o  obj/serial/cg.o -lm -lrt -lstdc++ -L/home/brx-dchester/local/caliper/lib64 -lcaliper -lcaliper-mpi -lcaliper-reader -lcaliper-common -lcaliper-mpi-common  -o tealeaf.serial
/usr/bin/ld: /home/brx-dchester/local/caliper/lib64/libcaliper-mpi-common.a(aggregate_over_mpi.cpp.o): in function `(anonymous namespace)::recursive_append_path(cali::CaliperMetadataAccessInterface const&, cali::Node const*, cali::NodeBuffer&, std::set<unsigned long, std::less<unsigned long>, std::allocator<unsigned long> >&)':
aggregate_over_mpi.cpp:(.text+0x14c): undefined reference to `cali::NodeBuffer::append(cali::Node const*)'
/usr/bin/ld: /home/brx-dchester/local/caliper/lib64/libcaliper-mpi-common.a(aggregate_over_mpi.cpp.o): in function `(anonymous namespace)::pack_and_send(int, cali::CaliperMetadataAccessInterface&, cali::Aggregator&, int)::{lambda(cali::CaliperMetadataAccessInterface&, std::vector<cali::Entry, std::allocator<cali::Entry> > const&)#1}::operator()(cali::CaliperMetadataAccessInterface&, std::vector<cali::Entry, std::allocator<cali::Entry> > const&) const':
aggregate_over_mpi.cpp:(.text+0x2c8): undefined reference to `cali::SnapshotBuffer::append(cali::CompressedSnapshotRecord const&)'
/usr/bin/ld: /home/brx-dchester/local/caliper/lib64/libcaliper-mpi-common.a(aggregate_over_mpi.cpp.o): in function `(anonymous namespace)::pack_and_send(int, cali::CaliperMetadataAccessInterface&, cali::Aggregator&, int)':
aggregate_over_mpi.cpp:(.text+0x31c): undefined reference to `cali::NodeBuffer::NodeBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x324): undefined reference to `cali::SnapshotBuffer::SnapshotBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x454): undefined reference to `cali::SnapshotBuffer::~SnapshotBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x45c): undefined reference to `cali::NodeBuffer::~NodeBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x484): undefined reference to `cali::SnapshotBuffer::~SnapshotBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x494): undefined reference to `cali::NodeBuffer::~NodeBuffer()'
/usr/bin/ld: /home/brx-dchester/local/caliper/lib64/libcaliper-mpi-common.a(aggregate_over_mpi.cpp.o): in function `(anonymous namespace)::receive_and_merge_nodes(int, cali::CaliperMetadataDB&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > >&, int)':
aggregate_over_mpi.cpp:(.text+0x578): undefined reference to `cali::NodeBuffer::NodeBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x590): undefined reference to `cali::NodeBuffer::import(unsigned long, unsigned long)'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x5e0): undefined reference to `cali::NodeBuffer::for_each(std::function<void (cali::NodeBuffer::NodeInfo const&)>) const'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x600): undefined reference to `cali::NodeBuffer::~NodeBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x624): undefined reference to `cali::NodeBuffer::~NodeBuffer()'
/usr/bin/ld: /home/brx-dchester/local/caliper/lib64/libcaliper-mpi-common.a(aggregate_over_mpi.cpp.o): in function `(anonymous namespace)::receive_and_merge_snapshots(int, cali::CaliperMetadataDB&, std::map<unsigned long, unsigned long, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, unsigned long> > > const&, std::function<void (cali::CaliperMetadataAccessInterface&, std::vector<cali::Entry, std::allocator<cali::Entry> > const&)>, int)':
aggregate_over_mpi.cpp:(.text+0x6d0): undefined reference to `cali::SnapshotBuffer::SnapshotBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x6ec): undefined reference to `cali::SnapshotBuffer::import(unsigned long, unsigned long)'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x864): undefined reference to `cali::SnapshotBuffer::~SnapshotBuffer()'
/usr/bin/ld: aggregate_over_mpi.cpp:(.text+0x8a0): undefined reference to `cali::SnapshotBuffer::~SnapshotBuffer()'
collect2: error: ld returned 1 exit status
make: *** [Makefile:44: tealeaf] Error 1

**Comment by daboehme** [comment]
Try putting `-lcaliper-mpi-common` in front of `-lcaliper-common` on the link line. Sorry about this mess. 

Using shared libraries is typically easier. I'll update documentation on using Caliper with MPI and static linking.

**Comment by deanchester** [comment]
Thats fixed it now. Thanks for the help. Another quick question is it recommended to put that function in my code regardless to ensure it always picks up the MPI stuff?

**Comment by daboehme** [comment]
Great! 

Yes, you can leave `cali_mpi_init()` function in the code all the time. It doesn't do much, it's really just there for the linker to pull in the MPI stuff.

**Comment by daboehme** [comment]
Issue seems to be resolved - closing this.
