### ISSUE TITLE
Need simpler API for Caliper config

### ISSUE THREAD

**Issue by mplegendre** [LLNL/Caliper#172]
@daboehme as we discussed in person, I need a simpler API for Caliper configuration for application integration.  The use case is that an application may get configured from the command line or input deck, ala:

./myapp --caliper=<some string>

An example of <some string> might be "spot,mpi,topdown"

I'd like to get the parsing and configuration settings based on <some string> inside Caliper, rather than have it in the application.  That way we can expand Caliper capabilities without having to go back to the option parsing of each application that integrated Caliper.

We'll also need some of kind of error checking for <some string>, which is separate from the configuration.  Many apps will want to check whether they were passed a valid string before they move on to initialize phase, and only Caliper will know whether the string is valid.

**Comment by daboehme** [comment]
This was addressed with the ConfigManager API integrated in d5f056ad1f9b5a639039ea5b1eac453b3e18d692 and subsequent commits.
