### ISSUE TITLE
Issue building to get CPU Information

### ISSUE THREAD

**Issue by deanchester** [LLNL/Caliper#180]
Hi, 

I was trying to build on Centos 6.10 with the following compiler and this line needed to change from 

    if (syscall(SYS_getcpu, &cpu, &node, NULL) == 0)

to: 
  
    if (syscall(SYS_get_cpu, &cpu, &node, NULL) == 0)

I am compiling with GCC 7.3.0. 

Don't know whether its just specific to my system or it has changed recently. 

Kind Regards, 

Dean 

https://github.com/LLNL/Caliper/blob/a3204adff310274123b3879362429e1bf15dc534/src/services/cpuinfo/CpuInfo.cpp#L28

**Comment by daboehme** [comment]
Hi Dean,

Thanks for the report. I believe it is and should be SYS_getcpu - haven't seen SYS_get_cpu anywhere else, and CentOS 6 is based on a rather dated kernel by now. I can add some #ifdefs around it to make sure it compiles.

**Comment by klevzoff** [comment]
Hi, @daboehme 

Unfortunately, the above fix renders the code uncompilable when `SYS_getcpu` is not defined, due to a misplaced `#endif`. Could you fix please? I can open a new issue if needed.

Many thanks,
Sergey

**Comment by daboehme** [comment]
Hi @klevzoff ,

You're right, sorry about that. This should be fixed with 46ed22f.
