### ISSUE TITLE
CALI_ATTR_HIDDEN seems underutilized

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#199]
I was writing up a PR to introduce this new attribute for Caliper Attributes, `CALI_ATTR_INTERNAL`, which wouldn’t show up in output services, when I realized it already exists as `CALI_ATTR_HIDDEN`. Why aren’t cali.event.[begin/set/end] CALI_ATTR_HIDDEN, also cali.caliper.version and maybe cali.channel? This would reduce the number of times you need to specify a query for the `report` service.

Am I missing something there?

**Comment by daboehme** [comment]
Glad you found the hidden flag :) You're right that cali.event.[begin/set/end] should probably be hidden. I'll get that fixed. I think we can do that for .version and .channel, too.

**Comment by DavidPoliakoff** [comment]
You've addressed this, sorry for leaving it stale
