### ISSUE TITLE
Apparent silent failure with with WITH_CALLPATH

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#211]
Hey folks,

I've been trying to build with callpath support (which requires libunwind). I think what I need to do for this is turn WITH_CALLPATH=ON (let me know if I need to do more). Unfortunately, I screwed up and didn't have libunwind loaded. In this instance it looks like Caliper silently just doesn't give me libunwind/callpath service.

I think this is a holdover from when Caliper enabled services by default, but didn't yell if it couldn't enable them, I think a better behavior would be that if somebody requests the callpath service and doesn't get it, we should error out.

Apologies if I'm missing something obvious

**Comment by daboehme** [comment]
Hm, you should have gotten a `== CALIPER: Warning: service "callpath" not found` message. So you didn't get that? Is the callpath service in the list of service when you run with `CALI_LOG_VERBOSITY=2`?

**Comment by DavidPoliakoff** [comment]
@daboehme : I'm having a stupid moment. Caliper prints a warning, I just didn't spot it. To wit:

```
-- Could NOT find Libunwind (missing: LIBUNWIND_LIBRARIES LIBUNWIND_INCLUDE_DIRS)
CMake Warning at CMakeLists.txt:170 (message):
  Callpath support was requested but libunwind was not found!
```

Oops. Thanks for the patience

**Comment by DavidPoliakoff** [comment]
Actually, whether that should be a warning or an error is worth considering, but this was user error
