### ISSUE TITLE
More details in human-readable table

### ISSUE THREAD

**Issue by mrzv** [LLNL/Caliper#226]
I'd like to print out a detailed trace of when different events begin and end. I can figure it out from the raw traces, but not from the human-readable table, `cali-query -t`, at least not easily. I'm wondering if there is some way to get all the details in the human-readable form.

Here's an example:
```
#include <caliper/cali.h>
#include <caliper/common/Variant.h>

#include <chrono>
#include <thread>

int main()
{
    CALI_MARK_BEGIN("A");
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    CALI_MARK_BEGIN("B");
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    CALI_MARK_BEGIN("C");
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    CALI_MARK_END("C");

    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    CALI_MARK_END("B");

    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    CALI_MARK_END("A");
}
```
I compile and run it with
```
CALI_SERVICES_ENABLE=event,recorder,trace,mpi,timestamp CALI_TIMER_OFFSET=true ./test-caliper
```
If I now ask for the table, I get:
```
$ cali-query -t *.cali -S time.offset
time.offset annotation time.inclusive.duration 
        219 
     100376 A          
     200582 A/B        
     400961 A/B/C                       200379 
     501152 A/B                         400776 
     601319 A                           601100 
```

The `time.offset`s puzzle me here. For instance, A really begins at 219. You can figure it out either from the full trace (`*.cali`), or from the second `A` line, timestamp - duration (219 = 601319 - 601100). Similar story applies to other events. `B` really starts at 100376. Again obvious from the trace, but also from the end timestamp 100376 = 501152 - 400776.

My questions are:
1. Why this strange output for the beginning time? It feels like all the labels are shifted somehow.
2. Is there a way to get cali-query to output the time.offset for `event.begin` and `event.end` (ideally with other annotations, like `mpi.rank` included)?

**Comment by mrzv** [comment]
I should add that the best way I found so far to get what I want is to run
```
cali-query -t *.cali -S time.offset -q "SELECT * WHERE event.end#annotation" 
```
and then do the arithmetic from `time.offset` and `time.inclusive.duration`. But this requires two passes over the data to order the begin and end events, and in general seems suboptimal.

**Comment by mrzv** [comment]
One more question: is there a way to make `-t` output comma-separated, rather than space-aligned? I want to parse it with an external tool, and I don't have much faith in splitting it up based on spaces (since some attributes might be missing).

**Comment by daboehme** [comment]
Hi @mrzv ,

Sorry for the late response, was out of the office for a while. For your first question, you're right that A begins at timestamp 219. The "annotation" column marks what is currently on the stack for each event, so the second line where annotation=A is really the begin event for A/B, where we're currently in A but not yet in B. As you found, looking for `event.begin#annotation` and `event.end#annotation` will show you which begin/end event it is.

To get machine-readable output, I'd recommend either the `-e` option for cali-query (which prints a comma-separated key-value list for each record) or json output with `-j`.

**Comment by mrzv** [comment]
@daboehme Thanks for `-e`; it's very helpful.

**Comment by mrzv** [comment]
@daboehme BTW, the reason I ask all this is that I added ability to visualize Caliper traces to a little [profile visualizer](https://github.com/mrzv/profvis) I wrote. It might be useful to others. (The docs are "sparse", but if you just compile and run it, the behavior will be obvious.)

**Comment by daboehme** [comment]
Seems to be resolved.
