### ISSUE TITLE
It would be nice if get_config_docstrings() would also display caliper version

### ISSUE THREAD

**Issue by mcfadden8** [LLNL/Caliper#251]
I am currently using `cali::ConfigManager::get_config_docstrings()` for displaying caliper help within including programs.  It would be handy if caliper version information could also be included along with the configuration help.

**Comment by daboehme** [comment]
I wouldn't put it in the ConfigManager API as this is strictly about the config manager options, but I can add a `cali_caliper_version()` call that returns the version string.

**Comment by mcfadden8** [comment]
That would be perfect.  Do we want to close this or simply update the title?

**Comment by daboehme** [comment]
Keep it open, I'll add that API call in an upcoming pull request that will close the ticket.
