### ISSUE TITLE
cali-graph

### ISSUE THREAD

**Issue by jgphpc** [LLNL/Caliper#263]
Hi,

[tools.rst](https://github.com/LLNL/Caliper/blob/master/doc/sphinx/tools.rst#cali-graph) mentions the `cali-graph` tool
but it has been removed in https://github.com/LLNL/Caliper/commit/684c522
Is it now part of another tool or definitely no longer supported ?

Thanks,

**Comment by daboehme** [comment]
Hi @jgphpc ,

Thanks for the comment. The cali-graph tool was more of a debug tool for Caliper. I removed it from the code because it wasn't really used much, but I forgot to remove it from the documentation - I'll fix that. Did you need it for anything?

**Comment by jgphpc** [comment]
@daboehme no special need,i was just looking at the doc to get used to Caliper.
First tests look promising, thanks !
