### ISSUE TITLE
cali_begin_int* takes an int in c, and an int64 in fortran

### ISSUE THREAD

**Issue by trws** [LLNL/Caliper#3]
What is the supported interface for passing a sized integer, or pointer type, from C?  Is there a plan to have specific-sized int setters, or use the generic set for sized integers?

**Comment by daboehme** [comment]
The Fortran `cali_begin_int` takes a regular Fortran integer as value parameter, which I had hoped is the same as a C integer, but I might be wrong (I wouldn't be surprised, the more you learn about Fortran the worse it gets).

For 64-bit ints you can use the generic begin/set. In fact for `CALI_TYPE_(U)INT`, begin/set _expects_ 64-bit values; it's a bad idea to put something else in. The `begin/set_int*` functions handle the conversion. If needed I can add size-specific functions.

**Comment by trws** [comment]
The one that actually worries me a bit more is the assumption that pointer and int are the same size. There are a few platforms where that doesn't hold, even in 64bit mode, and using the generic functions works but is less self documenting.


________________________________

**Comment by trws** [comment]
As an example, on my 64-bit mac:

```
sizeof((int)0):4
sizeof((intptr_t)0):8
```

**Comment by daboehme** [comment]
For pointers there's the `CALI_TYPE_ADDR` type. There's no high-level setter for it yet, but you can set it through the generic interface. Internally it's handled as a (64-bit) uint for the most part, except it is printed in hexadecimal when converted to string.

**Comment by daboehme** [comment]
This is ancient, but we finally have proper size-specific int setters for variants.

**Comment by trws** [comment]
That's excellent, thanks @daboehme.  @StevWonder, not sure how active the caliper usage is, but this might help shore up some potential future issues if it's in use.
