### ISSUE TITLE
Performance Metrics for GPU-enabled code

### ISSUE THREAD

**Issue by rcarson3** [LLNL/Caliper#324]
@daboehme I'm currently using caliper to get basic timing information out of my code ExaConstit which is used within an ECP application. As part of this ECP app, we're currently looking at various different performance tools (TAU,HPCToolkit, and etc) to potentially get out such information as FLOP or tracking memory/ memory usage. I was wondering if either of these were possible in Caliper for GPU code. 

I've tried using the PAPI feature to get at the FLOP metric based on the config file for LULESH in the caliper-example repo on Lassen and have been striking out with that.

**Comment by daboehme** [comment]
Hi @rcarson3 ,

Getting HW counters like FLOP counts from GPU kernels is not straightforward. For GPU FLOP metrics and such we generally recommend the NVidia NSight tools (nsys and ncu, or the older nvprof). You can forward Caliper-annotated code regions to the NVidia tools with the "nvtx" service ("nprof" in Caliper <= 2.4), e.g.
```
CALI_SERVICES_ENABLE=nvtx ncu --nvtx ./app
```

You can then use Caliper annotations to only profile a specific region - check the NVidia tools documentation.

You can also use Caliper to profile CUDA API calls, or trace GPU activities (kernel execution, memcopies, etc.). For both of these you'll need to build Caliper with CUpti support. CUDA API profiling is supported for many built-in configs, e.g.
```
CALI_CONFIG=runtime-report,profile.cuda ./app
```
Activity tracing reports time on the device and host for CUDA activities:
```
CALI_CONFIG=cuda-activity ./app
```

While we currently don't support GPU metrics directly in Caliper, PAPI has a CUDA component - if you get that to work then Caliper should be able to read these metrics via the PAPI service. However, it looks like the PAPI CUDA component is no longer supported on newer devices. I also don't think we have a PAPI installation on Lassen, so you'd have to build it yourself. May be worth a try.
