### ISSUE TITLE
[Question] How to make a Spot profile output a cali file with a specific name

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#332]
So I've moved over to using CALI_CONFIG to do most of my Caliper configuration, thanks for that. One question I have is how to do one of these configs with a small change. Specifically, I want to output .cali files that are named for the date. Actually, the full idea is to allow users to specify that something is the "reference" run, which will output "reference.cali", and then use the Hatchet Jupyter notebook to compare latest Kokkos to that "reference" one

edit: got distracted. The main question I need is "how do I say 'do CALI_CONFIG=spot(profile.kokkos=true)' except also specify the recorder service output?"

**Comment by daboehme** [comment]
The spot config (like pretty much all configs) has an "output" option where you can specify a filename, e.g. `spot(profile.kokkos,output=reference.cali)"`. You can also use use attributes in the filename, e.g. `output=%mpi.rank%.cali`, though I'm not entirely sure if that works with global attributes. For a date you can just generate a filename with Unix `date` of course.

**Comment by DavidPoliakoff** [comment]
Damn you're good ;)
