### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ibaned** [LLNL/Caliper#367]
Does Caliper work on Windows?

**Comment by daboehme** [comment]
Not natively. It does work inside WSL2.

**Comment by ibaned** [comment]
@daboehme thanks for the prompt response! Unfortunately native support is a requirement for me. It would be great if this could be added at some point!

**Comment by daboehme** [comment]
I'll consider it closed with #388

**Comment by jrmadsen** [comment]
@daboehme Could you ping me when you generate a release with this support? When it's released I'd like to remove forcing disabling Caliper support in timemory when the build system detects windows.

**Comment by daboehme** [comment]
@jrmadsen It's in v2.7.0 already. It is limited to basic functionality only though, so most optional services or Gotcha won't be supported. I also haven't tested it myself.
