### ISSUE TITLE
A little more rigor in prefixing CALI in CMake options

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#37]
I've been looking at integrating Caliper into someone else's large build. As part of that, I found myself having to set [BUILD_TESTING](https://github.com/LLNL/Caliper/blob/master/CMakeLists.txt#L44) to OFF in order to make Caliper not integrate GTest. Could you do a once-over and make that (and anything else that might not be Caliper-exclusive nomenclature) CALI_BUILD_TESTING? I worry that somebody else has BUILD_TESTING as an option that means something else, and we wind up being the source of a nasty bug.

**Comment by daboehme** [comment]
Agree that that's a good idea. Needs to be coordinated a bit, as it will require an update to the Spack package. And probably documentation.

**Comment by DavidPoliakoff** [comment]
Apparently we managed this one by just not enabling BUILD_TESTING by default
