### ISSUE TITLE
MPI Issues with OpenMPI

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#39]
https://github.com/LLNL/Caliper/blob/master/mpi/caliper-mpi/aggregate_over_mpi.cpp#L98

This line's nodebuf, and the snapbuf equivalent immediately below, appear to be const char*, where MPI expects a void*, and in some configurations this will cause you grief. I'm not sure how you want to handle this, a static_cast would be reasonable, but wanted you to be aware that this can break in some (interesting) builds.

**Comment by daboehme** [comment]
I guess that's with ancient MPIs that don't use const ptrs for Send. Which one do you use?
