### ISSUE TITLE
2.6.0 Issue setting the max column width

### ISSUE THREAD

**Issue by corbett5** [LLNL/Caliper#393]
I'm using Caliper 2.6.0 and when I pass `runtime-report,max_column_width=200` to the `ConfigManager` I get this error

`== CALIPER: (0): runtime-report: mpireport: config parse error: Unknown formatter`

This has worked in the past, although I don't remember exactly what version I was using. Without the ability to set the column width it makes it much harder to grok.

**Comment by daboehme** [comment]
Hi @corbett5 ,

Thanks for reporting. The `max_column_width` option was indeed broken in v2.6.0, but it's fixed in the upcoming v2.7.0 release. I'm planning to publish v2.7.0 sometime next week, in the meantime you can try the current master branch.

**Comment by corbett5** [comment]
Great, I'll just wait then. Thanks!
