### ISSUE TITLE
[feature request] Pkg-config package for non-cmake builds

### ISSUE THREAD

**Issue by trws** [LLNL/Caliper#4]
Just for ease of building against Caliper, in a non-cmake context, a pkg-config file would be great.

**Comment by daboehme** [comment]
I added one in the latest commit - let me know if that works.

**Comment by trws** [comment]
The file works perfectly @daboehme, thanks!  The one thing that would be good before closing this would be to install it to <prefix>/share/pkgconfig rather than lib.  It's a nitpick, but it's where these things go by default for most packages.
