### ISSUE TITLE
loop gets renamed unexpectedly

### ISSUE THREAD

**Issue by ibaned** [LLNL/Caliper#400]
I am profiling a loop like this:
```cpp
CALI_CXX_MARK_LOOP_BEGIN(pc_loop, "predictor-corrector");
```
But when I look at this loop in the SPOT web interface it got renamed to `a0or-corrector`. Is there some part of the code that renames the word "predict"?

**Comment by daboehme** [comment]
There shouldn't be. Can you run `cali-query -t <file.cali>` on the Caliper file and see what it prints?

**Comment by ibaned** [comment]
Yes, here is the view of SPOT I'm seeing:
<img width="407" alt="Screen Shot 2021-11-11 at 2 28 34 PM" src="https://user-images.githubusercontent.com/971921/141371615-b668be77-eac5-482f-8d6e-796d8241cbef.png">

And here is the output of `cali-query -t`:
[cali_query.txt](https://github.com/LLNL/Caliper/files/7523373/cali_query.txt)

**Comment by daboehme** [comment]
Thanks. Looks like the name is correctly preserved in the Caliper file, so I suspect the issue is in SPOT. Something might have gone wrong with SPOT's new name compression scheme. Let's have @aschwanden1 take a look at it.

**Comment by ibaned** [comment]
Thanks! do you want me to open an issue on the `spot2_container` repository?

**Comment by daboehme** [comment]
> Thanks! do you want me to open an issue on the `spot2_container` repository?

Yes, I think that would be a good idea. It might help to attach the .cali file.

**Comment by ibaned** [comment]
Closing because Caliper seems to be not at all at fault here.
