### ISSUE TITLE
Issue with Intel Complier 

### ISSUE THREAD

**Issue by KokoFan16** [LLNL/Caliper#407]
$ cmake -DWITH_MPI=1 ..
-- The C compiler identification is Intel 19.1.0.20191121
-- The CXX compiler identification is Intel 19.1.0.20191121
-- Cray Programming Environment 2.6.5 C
-- Check for working C compiler: /opt/cray/pe/craype/2.6.5/bin/cc
-- Check for working C compiler: /opt/cray/pe/craype/2.6.5/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.6.5 CXX
-- Check for working CXX compiler: /opt/cray/pe/craype/2.6.5/bin/CC
-- Check for working CXX compiler: /opt/cray/pe/craype/2.6.5/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found MPI_C: /opt/cray/pe/craype/2.6.5/bin/cc (found version "3.1") 
-- Found MPI_CXX: /opt/cray/pe/craype/2.6.5/bin/CC (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.12") 
-- Performing Test Supports_Wall_Flag
-- Performing Test Supports_Wall_Flag - Success
-- Caliper configuration summary:
-- Caliper version           : 2.8.0-dev
-- Build type                : 
-- Compiler                  : Intel 19.1.0.20191121 (/opt/cray/pe/craype/2.6.5/bin/CC)
-- System                    : Linux-4.12.14-197.99-default (x86_64)
-- Install dir               : /usr/local
-- Build shared libs         : FALSE
-- Build Caliper tools       : ON
-- Build tests               : OFF
-- Fortran support           : No
-- cpuinfo support           : Yes
-- memusage support          : Yes
-- adiak support             : No
-- GOTCHA support            : Yes, using internal
-- PAPI support              : No
-- Libdw support             : No
-- Libpfm support            : No
-- Libunwind support         : No
-- Sampler support           : No
-- SOSFlow support           : No
-- MPI support               : Yes, using 
-- MPIWRAP support           : Yes, using GOTCHA
-- MPIT support              : No
-- OMPT support              : No
-- Nvtx support              : No
-- CUpti support             : No
-- Kokkos support            : Yes
-- RocTracer support         : No
-- RocTX support             : No
-- TAU support               : No
-- VTune support             : No
-- PCP support               : No
-- histogram support         : No
-- variorum support          : No
-- Configuring done
-- Generating done

$ make 
[  6%] Built target caliper-gotcha
[ 10%] Built target caliper-mpiwrap
[ 23%] Built target caliper-common
[ 29%] Built target caliper-interface
[ 43%] Built target caliper-reader
[ 44%] Built target gen-services
[ 57%] Built target caliper-services
[ 59%] Built target caliper-kokkos
[ 59%] Built target caliper-ioservice
[ 62%] Built target caliper-CurIOus
[ 62%] Built target caliper-pthread
[ 64%] Built target caliper-sysalloc
[ 65%] Built target caliper-spot
[ 65%] Building CXX object src/caliper/CMakeFiles/caliper-runtime.dir/AnnotationBinding.cpp.o
icpc: error #10106: Fatal error in /opt/intel/compilers_and_libraries_2020.0.166/linux/bin/intel64/mcpcom, terminated by kill signal
compilation aborted for Caliper/src/caliper/AnnotationBinding.cpp (code 1)
make[2]: *** [src/caliper/CMakeFiles/caliper-runtime.dir/build.make:87: src/caliper/CMakeFiles/caliper-runtime.dir/AnnotationBinding.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1239: src/caliper/CMakeFiles/caliper-runtime.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Do you have any idea about this issue?

**Comment by daboehme** [comment]
On a quick try I can't reproduce this with an Intel 19.1.0 installation on our clusters. What system is this on? Looks like a Cray? 

Either way, this seems to be an internal compile error in icpc so there's probably not much I can do about it. You can try building Caliper with gcc or clang and link it to the target code.

**Comment by jrmadsen** [comment]
> this seems to be an internal compiler error in icpc

My first thought when I saw `terminated by kill signal` was an OOM error (I run into this a lot bc of how much memory compiling templates can consume). And I think that guess is supported by [this](https://community.intel.com/t5/Intel-C-Compiler/icpc-error-10106-Fatal-error/m-p/1157248#M35409). 

I've never seen Caliper require much memory to compile but if that was a login node at NERSC or something, it's likely there was someone compiling or running something on the login node that was taking up a lot of memory.

**Comment by daboehme** [comment]
> My first thought when I saw `terminated by kill signal` was an OOM error (I run into this a lot bc of how much memory compiling templates can consume). And I think that guess is supported by [this](https://community.intel.com/t5/Intel-C-Compiler/icpc-error-10106-Fatal-error/m-p/1157248#M35409).

Good point. @KokoFan16 , can you just try re-running the compilation and see if this was the issue?

**Comment by KokoFan16** [comment]
The issue is gone after I re-ran it, so I will close the issue now. Thanks.
