### ISSUE TITLE
Openmp support

### ISSUE THREAD

**Issue by QYChan** [LLNL/Caliper#503]
I want to use Caliper to profiler my openmp program on ubuntu. When I install Caliper, the following error occurred:
```bash
/Caliper/src/services/ompt/OmptService.cpp:11:10: fatal error: omp-tools.h: No such file or directory
 #include <omp-tools.h>
```
As mentioned in the [document](https://software.llnl.gov/Caliper/OpenMP.html#omp-instrumentation)
```text
Caliper can profile OpenMP constructs with the help of the OpenMP tools interface (OMPT). This requires a compiler with OMPT support, e.g. clang 9+. Build Caliper with -DWITH_OMPT=On to enable it.
```
Dose the OpenMP option only support for clang 9+ currently? I use GCC/G++ on ubuntu 18.

**Comment by daboehme** [comment]
Hi @QYChan , yes the OpenMP support in Caliper relies on the OpenMP tools interface (OMPT), which is not AFAIK not available in older GCCs.
