### ISSUE TITLE
Standardize Unit Metadata

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/Caliper#71]
Your daily issue from me! Also pinging @alfredo-gimenez for no reason whatsoever:

```
qyburn:build poliakoff1$ cali-query -q "SELECT * FORMAT JSON()" --list-attributes *.cali
[
...
{"class.aggregatable":"true","time.unit":"usec","cali.attribute.prop":"85","cali.attribute.type":"uint","cali.attribute.name":"time.inclusive.duration","attribute.id":55}
...
]
```
Here we do something that is so close to perfect, we record the units of our metrics. However, the way in which they're recorded is (I imagine) nonstandard, we have "time.unit" for this unit, somebody else might have (the equivalent of) "time.inclusive.duration.unit," and that might be correct. I'd like it if in the same way we know that time.inclusive.duration is a "uint", we know that it's in units of "usec."

My end goal is to replace (augment?) "time.inclusive.duration" with "usec" on the y-axis labels

![screen shot 2017-11-15 at 9 56 52 am](https://user-images.githubusercontent.com/4220361/32851976-6d2b3e6c-c9eb-11e7-839d-c210ab03a1c7.png)

**Comment by DavidPoliakoff** [comment]
Additional useful things would be recording what attributes are "metrics," that will be useful to any viz tools we decide to use. Not all uints are metrics. Basically could you write Scrubjay into Caliper?

**Comment by daboehme** [comment]
Seems we generally should discuss what kind of metadata would be useful on attributes. We can probably benefit from experiences with ScrubJay there. I'll put it on the agenda for one of the next meetings.

**Comment by alfredo-gimenez** [comment]
Absolutely! The metadata class makes it possible already, but we need to enforce standard semantics so we can just e.g. dump out a ScrubJay .dsid (json format containing sj semantics). 

I also plan on making a service to generate an Avro schema for specified columns, that way we can instantiate a direct Kafka ingestion point through config variables, e.g. `CALI_KAFKA_INGEST_COLUMNS=time,phase` and `CALI_KAFKA_TOPIC=lulesh-caliper-topic`

**Comment by DavidPoliakoff** [comment]
Yeah I think (?) Adiak is a good place to start on this, closing
