### ISSUE TITLE
A question about accessing memory information

### ISSUE THREAD

**Issue by codinglzc** [LLNL/Caliper#72]
Hello there!
After I finished Caliper documentation, I still did not know how to use Caliper flexibly.
If I have a program, and after running this program, how to see memory access information of the program through Caliper? The more information I hope to get the memory access, the better, the more detailed the better.
Thanks very much!

**Comment by alfredo-gimenez** [comment]
See [this example configuration file](https://github.com/LLNL/Caliper/blob/master/examples/configs/sampled_memory_trace_pebs.conf) for how to obtain sampled memory accesses, and [this example code](https://github.com/LLNL/Caliper/blob/master/examples/apps/cali-memtracking.cpp) for how to annotate memory allocations. You can also enable the `alloc` service to track and record memory allocations. I'll make a note to add the alloc service to the docs, which I now realize is missing. If you have a specific issue getting these to work please post the details.

**Comment by codinglzc** [comment]
Hello!
I have done as you said. 
`caliper.config:`
> CALI_SERVICES_ENABLE=libpfm:pthread:recorder:trace:symbollookup:callpath:alloc:instlookup
 CALI_LIBPFM_EVENT_LIST=MEM_TRANS_RETIRED:LATENCY_ABOVE_THRESHOLD
 CALI_LIBPFM_PERIOD=10000
 CALI_LIBPFM_PRECISE_IP=2
 CALI_LIBPFM_CONFIG1=20
 CALI_LIBPFM_SAMPLE_ATTRIBUTES=ip,time,tid,cpu,addr,weight,data_src
 CALI_RECORDER_FILENAME=sampled_memory_trace.cali

`cali-memtracking.cpp:` is the same as [cali-memtracking.cpp](https://github.com/LLNL/Caliper/blob/master/examples/apps/cali-memtracking.cpp)

when I run following instruction:
> $ g++ -o cali-memtracking cali-memtracking.cpp -L/opt/Caliper/lib -lcaliper -lcaliper-tools-util -std=c++11
 $ ./cali-memtracking

I get this result:
> == CALIPER: Registered callpath service
== CALIPER: libpfm: program started with SIGIO masked, unmasking it now
== CALIPER: Registered libpfm service
== CALIPER: Registered pthread service
== CALIPER: Registered alloc service
== CALIPER: Registered recorder service
== CALIPER: Registered trace service
== CALIPER: Warning: service "symbollookup" not found
== CALIPER: Warning: service "instlookup" not found
== CALIPER: Initialized
== CALIPER: libpfm: cannot attach event cycles
== CALIPER: libpfm: fcntl SETFL failed
== CALIPER: libpfm: fcntl SETOWN failed
== CALIPER: libpfm: fcntl SETSIG failed
== CALIPER: libpfm: cannot mmap buffer for event cycles
== CALIPER: libpfm: cannot reset counter for event cycles
== CALIPER: libpfm: cannot enable event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 1.54828e+26
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 1.54658e+26
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 3.09395e+26
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 4.63987e+26
== CALIPER: Flushing Caliper data
== CALIPER: Trace: Flushed 12 snapshots.
== CALIPER: libpfm: cannot disable event cycles
== CALIPER: libpfm: thread sampling stats:
== CALIPER: libpfm: thread 0	signals received: 0	samples produced: 0	bad samples: 0	unknown events: 0	null Caliper instances: 0
== CALIPER: Recorder: Wrote 70 records.

Now I do not know if this result is correct。

Thanks very much !

**Comment by alfredo-gimenez** [comment]
Thanks for the details!

First, in order to use your caliper configuration file, you have to set CALI_CONFIG_FILE, so try running 

CALI_CONFIG_FILE=/path/to/caliper.config ./cali-memtracking

Second, the events specified in CALI_LIBPFM_EVENT_LIST are requested, but they may not always be available, on which case this error occurs. You can obtain some of the available events through perf, by running 

perf list

Note that the example config file works on intel sandybridge and future core generations only, since it used a specific PEBS event name. The available events also depends on your available version of libpfm and your kernels version of perf_event.

**Comment by codinglzc** [comment]
Thanks for your guidance!
But I have done as you said, it seems to be still wrong. 

When I run the command `perf list`, what I got includes this one 
`L1-dcache-load-misses                              [Hardware cache event]`.

Then I `cd` into the `examples` directory of `perfmon2-libpfm4`  and run the command `./showevtinfo > showevtinfo.txt`. I see the output of libpfm’s showevtinfo tool by running `vim showevtinfo.txt` and find the `L1-dcache-load-misses` event. As follows:

>  #-----------------------------
 IDX  : 106954795
 PMU name : perf (perf_events generic PMU)
 Name     : L1-DCACHE-LOAD-MISSES
 Equiv    : PERF_COUNT_HW_CACHE_L1D:READ:MISS
 Flags    : None
 Desc     : L1 cache load misses
 Code     : 0x0
  #-----------------------------

My `caliper.config` is as follows:

> CALI_CONFIG_PROFILE=cali-basic-libpfm
 #[cali-basic-libpfm]
 CALI_SERVICES_ENABLE=libpfm:pthread:recorder:trace:symbollookup:callpath:alloc:inst    lookup
 CALI_LIBPFM_EVENT_LIST=L1-DCACHE-LOADS
 CALI_LIBPFM_PERIOD=10000
 #CALI_LIBPFM_PRECISE_IP=2
 #CALI_LIBPFM_CONFIG1=0
 CALI_LIBPFM_SAMPLE_ATTRIBUTES=ip,time,tid,cpu,addr,weight,data_src
 CALI_RECORDER_FILENAME=sampled_memory_trace.cali

When I run following instruction: 
`CALI_CONFIG_FILE=/root/caliper_test/caliper.config ./cali-memtracking`

Unfortunately I get the same wrong result as the last time. As follows:
> == CALIPER: Registered callpath service
== CALIPER: libpfm: program started with SIGIO masked, unmasking it now
== CALIPER: Registered libpfm service
== CALIPER: Registered pthread service
== CALIPER: Registered alloc service
== CALIPER: Registered recorder service
== CALIPER: Registered trace service
== CALIPER: Warning: service "symbollookup" not found
== CALIPER: Warning: service "instlookup" not found
== CALIPER: Initialized
**== CALIPER: libpfm: cannot attach event cycles**
== CALIPER: libpfm: fcntl SETFL failed
== CALIPER: libpfm: fcntl SETOWN failed
== CALIPER: libpfm: fcntl SETSIG failed
== CALIPER: libpfm: cannot mmap buffer for event cycles
== CALIPER: libpfm: cannot reset counter for event cycles
== CALIPER: libpfm: cannot enable event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 1.54828e+26
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 1.54658e+26
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 3.09395e+26
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
== CALIPER: libpfm: failed to reset counter for event cycles
cSum = 4.63987e+26
== CALIPER: Flushing Caliper data
== CALIPER: Trace: Flushed 12 snapshots.
== CALIPER: libpfm: cannot disable event cycles
== CALIPER: libpfm: thread sampling stats:
== CALIPER: libpfm: thread 0	signals received: 0	samples produced: 0	bad samples: 0	unknown events: 0	null Caliper instances: 0
== CALIPER: Recorder: Wrote 70 records.

Excuse me, could you tell me where my mistake is?
Thanks a lot！

**Comment by alfredo-gimenez** [comment]
Ah, there is a bug in the documentation! The variable is `CALI_LIBPFM_EVENTS` not `CALI_LIBPFM_EVENT_LIST`. My mistake! Updating the docs now.

The service is requesting "cycles" as the default event, because it doesn't see any config set for `CALI_LIBPFM_EVENTS`. You are correct to look for event names in libpfm's `showevtinfo` example, but keep in mind that not all events will allow sampling of memory addresses.

**Comment by codinglzc** [comment]
Thanks again for your guidance!
I still have a question. Caliper is a context annotation library for performance. Whenever I want to know a program's access information, I need to add the appropriate annotation in the code. Does this not make the user feel trouble? In Caliper, is there a way to get program access directly without having to add extra annotation? Suppose I have a lot of programs to test, and I do not need to be concerned about what the code looks like.

**Comment by alfredo-gimenez** [comment]
This is a design decision we made based on our work in performance optimization at the lab. A little bit of effort in making Caliper annotations creates a rich amount of possible analysis we can do and provides a lot of high-level information that makes analysis easier. Plus, doing optimizations usually requires modifying the code anyways.

The minimal amount of annotations is just a single line of code in the beginning of `main`:

```c
  CALI_MARK_FUNCTION_BEGIN;
```

That being said, we have also considered adding a driver code which simply initializes Caliper and enables data collection on previously compiled programs.

**Comment by daboehme** [comment]
Closing this - seems like the questions have been answered and there are no Caliper action items.
