### ISSUE TITLE
Unknown reason for more than 5X overhead

### ISSUE THREAD

**Issue by twang15** [LLNL/Caliper#77]
Caliper measured runtime is more than 5X than the actual.

The setting for measurement is as follows.

Application: Cloverleaf, https://github.com/UK-MAC/CloverLeaf
Caliper configuration: CALI_CONFIG_PROFILE=thread-trace
OMP configuration: 
export OMP_NUM_THREADS=8
export KMP_AFFINITY=verbose,granularity=fine,proclist=[0-7],explicit
Compiler: Intel icc/ifort
Machine: a Broadwell node

Data processing: 
cali-query -s time.inclusive.duration --table a.cali

Then, aggregate by loop names.

Sample output: format is <loop name, per-iteration runtime, loop total runtime, #loop iterations>
accelerate 7877.680 236330.400 30
cell1 4471.017 536522.000 120
cell2 3791.833 455020.000 120
cell3 5261.455 1262749.100 240
cell4 9991.950 2398068.100 240
cell5 4459.765 535171.800 120
cell6 3822.062 458647.500 120
cell7 6235.129 1496431.000 240
cell8 10099.415 2423859.600 240
dt 12053.170 361595.100 30
field 6103.430 183102.900 30
flux 6289.313 188679.400 30
gas 3801.574 250903.900 66
mom10 1879.398 902111.100 480
mom11 2650.991 1272475.900 480
mom12 2572.809 1234948.500 480
mom13 3468.235 1664752.900 480
mom14 3229.828 1550317.600 480
mom1 4523.797 1085711.400 240
mom2 4513.701 1083288.300 240
mom3 3827.700 918647.900 240
mom4 3845.044 922810.600 240
mom5 1886.059 905308.200 480
mom6 2651.195 1272573.600 480
mom7 2570.735 1233952.800 480
mom8 3288.488 1578474.000 480
mom9 3222.277 1546693.100 480
pdv1 9435.020 2264404.800 240
pdv2 10848.792 2603710.000 240
revert 3050.347 91510.400 30
viscosity 7645.947 229378.400 30

Sum of loop total runtime: 3.31482e+07 ms = 33.1482 seconds
Total runtime measured by timer:  5.5733
Runtime ratio of all the measured loops  is 92% of total runtime (Obtained by profiling)

I used similar settings for another benchmark before, and my impression is that caliper overhead is very low and neglectable.

Anybody knows why the overhead is so high for Cloverleaf?

Thanks a lot.

**Comment by daboehme** [comment]
Hi @twang15 ,

If I interpret this correctly, the loop times with a total of 33.14 seconds are reported by Caliper and the 5.57 seconds total runtime is reported by CloverLeaf's timer without Caliper instrumentation - is that correct?

Generally, the overhead depends on the granularity of the instrumentation. Based on the times given in the table (above 1000usec per iteration in each loop), there shouldn't be a 5X overhead -- if the loops are the only thing that is instrumented. Are there other Caliper annotations that are invoked much more frequently? 

You can see how many actions Caliper performs with the `statistics` service: set `CALI_SERVICES_ENABLE=statistics`. What does that report?

**Comment by twang15** [comment]
Hi @daboehme ,

1. Question: "the loop times with a total of 33.14 seconds are reported by Caliper and the 5.57 seconds total runtime is reported by CloverLeaf's timer without Caliper instrumentation - is that correct?"

Answer:  Yes.

2. Loops are the only thing that is instrumented. There are no other annotations.

To simplifying the problem, now there is only 1 caliper instrumentation as follows.

void advec_mom_kernel_1_c_(int x_min, int x_max,
    int y_min, int y_max,
    double *pre_vol, double *post_vol,
    double *volume, double *vol_flux_x,
    double *vol_flux_y)
{
  int k, j;
  **CALI_MARK_LOOP_BEGIN(mom1, "mom1");**
#pragma omp for private(j)
  for (k=y_min-2;k<=y_max+2;k++) {
#pragma ivdep
    for (j=x_min-2;j<=x_max+2;j++) {
      post_vol[FTNREF2D(j  ,k  ,x_max+5,x_min-2,y_min-2)]=volume[FTNREF2D(j  ,k  ,x_max+4,x_min-2,y_min-2)]
        +vol_flux_y[FTNREF2D(j  ,k+1,x_max+4,x_min-2,y_min-2)]
        -vol_flux_y[FTNREF2D(j  ,k  ,x_max+4,x_min-2,y_min-2)];
      pre_vol[FTNREF2D(j  ,k  ,x_max+5,x_min-2,y_min-2)]=post_vol[FTNREF2D(j  ,k  ,x_max+5,x_min-2,y_min-2)]
        +vol_flux_x[FTNREF2D(j+1,k  ,x_max+5,x_min-2,y_min-2)]
        -vol_flux_x[FTNREF2D(j  ,k  ,x_max+5,x_min-2,y_min-2)];
    }
  }
  **CALI_MARK_LOOP_END(mom1)**;
}

Caliper report: format above.
mom1 4498.983 1079755.900 240

We see that caliper-reported time 1079755.900 ms accounts for 19% of total runtime while profiler says it is around 2.5%.

3. how to extract the data after setting CALI_SERVICES_ENABLE=statistics?

**Comment by twang15** [comment]
Hi @daboehme ,

I figure out a solution, but I am not sure whether it is a bug in caliper or it is my misunderstanding of OMP parallel construct.

As an example, the original code looks like:

advec_mom_kernel_c_()
{
**#pragma omp parallel**
{
**#pragma omp for**
for loop 1

**#pragma omp for**
for loop 2
}
}

I outline for loop 1 (loop2 similar) to another file loop1.c as
loop1()
{
#pragma omp for
for loop 1
}

And then add caliper instrumentation as
loop1()
{
CALI_MARK_LOOP_BEGIN(mom1, "mom1");
**#pragma omp for**
for loop 1
CALI_MARK_LOOP_END(mom1);
}

The original file is changed as:
advec_mom_kernel_c_()
{
**#pragma omp parallel**
{
loop1();

loop2();
}
}

Then, I compile and run Cloverleaf. 
The result is correct and total runtime is as normal (before outlining), but caliper-measured time seems not correct as mentioned before.

The solution is as follows:
1. Outline loop1 (loop2 similar) as:
loop1()
{
**#pragma omp parallel for**
for loop 1
}

2. remove #pragma omp parallel in original file.
advec_mom_kernel_c_()
{
**//#pragma omp parallel**
{
loop1()
loop2()
}
}

Then, compile and run Cloverleaf. The result is correct and runtime is as normal.
Also, Caliper-measured time is consistent with what profilers report.

So, I guess it is a solution.
But, why does it work?
What is wrong with my first transformation? What doesn't it work with caliper but the results/runtime are correct?

**Comment by twang15** [comment]
Another question I have is as follows: (maybe I should report it as a separate issue)
For C/C++ program, there is a clean/simple macro CALI_MARK_LOOP_BEGIN/CALI_CXX_MARK_LOOP_BEGIN, I did not find a similar macro for Fortran and I really want one.

I did find an example in Caliper/src/fortran/main.f90, but it also records per-iteration timing. 
What I need is a macro/API similar to the one in C/C++ to measure end-to-end loop time and report it in a consistent format as the macro/API in C/C++ does.

cali-query -s time.inclusive.duration --table a.cali would report as follows:

loop time.inclusive.duration main
mom1                    4296
mom1                    4401
mom1                    4540
mom1                    4420 true
mom1                    4566 true
mom1                    4394 true
mom1                    4540 true
mom1                    4394 true
mom1                    4588 true
mom1                    4406 true
                     5472378 true

Instead of treating main in the same way as mom1 is treated, the report lists main in a separate row.
Any idea to avoid such an inconsistency in calieper data format between Fortran and C/C++?

**Comment by daboehme** [comment]
Hi @twang15 ,

When the Caliper loop annotations are inside the OpenMP parallel region, you will measure the time spent in the loop separately on each thread. When you then aggregate the times you will add them all together, which explains why they are much higher than what CloverLeaf reports: you're comparing the time over all threads with the time from one thread. As you have found out, the solution is to keep the Caliper annotations outside of the OpenMP parallel region.

As for the Fortran API: we currently don't have macros for Fortran, but you can get similar behavior with the Fortran API calls. E.g. for `CALI_MARK_LOOP_BEGIN/END` use:

    call cali_begin_string_byname('loop', 'mom1')
    do i = 1 .. n
       ...
    end do
    call cali_end_string_byname('loop')

For `CALI_MARK_FUNCTION_BEGIN/END` it would be

    call cali_begin_string_byname('function', 'main')
    ...
    call cali_end_string_byname('function')

**Comment by twang15** [comment]
It makes sense now.

There is no API cali_end_string_byname, so it should be cali_end_byname('loop')
in the following code:

call cali_begin_string_byname('loop', 'mom1')
do i = 1 .. n
   ...
end do
call cali_end_string_byname('loop')

**Comment by daboehme** [comment]
Good to know we could clarify this. 
You're right, it should be `cali_end_byname` to end the annotation in Fortran.
