### ISSUE TITLE
How can cali-query merge loop timing of the same loop but under different calling context?

### ISSUE THREAD

**Issue by twang15** [LLNL/Caliper#79]
Cali-query reports the following timing information: format <loop name, ms>
main 1000
main/gas 20
main/mom 20
gas 30

Is there a cali-query command line option to merge main/gas and gas together, so the report looks like:
main 1000
gas 50
mom 20

Thanks,
Tao

**Comment by daboehme** [comment]
You can try group by `event.end#loop`, e.g. `cali-query -q "SELECT event.end#loop, sum(time.inclusive.duration) GROUP BY event.end#loop FORMAT table`

**Comment by twang15** [comment]
[twang15@c94 R.new]$ cali-query -q "SELECT event.end#loop, sum(time.inclusive.duration) GROUP BY event.end#loop FORMAT table"  a.cali
== CALIPER: Registered event trigger service
== CALIPER: Registered pthread service
== CALIPER: Registered recorder service
== CALIPER: Registered timestamp service
== CALIPER: Registered trace service
== CALIPER: Initialized
**cali-query: error: unknown option: -q**

**Comment by daboehme** [comment]
The `-q` query syntax requires a newer version of Caliper. With older versions, `cali-query -t -a "sum(time.inclusive.duration)" --aggregate-key event.end#loop --print-attributes event.end#loop,time.inclusive.duration` should work.

**Comment by daboehme** [comment]
What do you mean by "extra tags"?

I think the `--print-attributes` syntax has changed, try `--print-attributes="event.end#loop:time.inclusive.duration"` (with ':' instead of comma and no spaces).

**Comment by twang15** [comment]
No, it does not work.

Sample output:
cali-query: processing 1 files using 1 thread.
__rec=node,attr=10,data=84,id=11,parent=3
__rec=node,attr=8,data=event.begin#loop,id=12,parent=11
__rec=node,attr=10,data=84,id=13,parent=2
__rec=node,attr=8,data=cali.snapshot.event.begin,id=14,parent=13

Extra tags mean:
**event.end#loop=**gas,**time.inclusive.duration=**246306
**event.end#loop=**viscosity,**time.inclusive.duration=**233972

While without them, the result should looks like:
loop time.inclusive.duration
gas 246306
viscosity 233972

**Comment by daboehme** [comment]
You still need `-t` etc. as well ... `cali-query -t -a "sum(time.inclusive.duration)" --aggregate-key event.end#loop --print-attributes="event.end#loop:time.inclusive.duration"` should do it.

**Comment by twang15** [comment]
It works well.
Thanks a lot!
