### ISSUE TITLE
Can caliper only record time for OMP master thread?

### ISSUE THREAD

**Issue by twang15** [LLNL/Caliper#80]
I have a code as follows:

#pragma OMP parallel for
for()
{
  for loop1
  for loop2
}

I want to measure runtime of loop1 and loop2 with caliper.
But simply adding instrumentation CALI_MARK_LOOP_BEGIN/END would not work, because the issue in #77.

So, I wonder whether there is caliper runtime configuration such that only the master thread runtime is measured. In this way, I can achieve my initial goal.

**Comment by daboehme** [comment]
You can add an annotation for the OpenMP thread ID and then filter by that. So, you do

    #pragma omp parallel for
    for(...) {
        cali_set_int_byname("thread.id", omp_get_thread_num());

        CALI_MARK_LOOP_BEGIN(...)
        for(...) { loop1; }
        CALI_MARK_LOOP_END(...)

        CALI_MARK_LOOP_BEGIN(...)
        for(...) { loop2; }
        CALI_MARK_LOOP_END(...)
    }

Then, you only select the master thread: `cali-query -s time.inclusive.duration:thread.id=0 ...`.

**Comment by twang15** [comment]
Thanks a lot!
I got the following report. 
What are the marked lines (line 1 and 4)?

loop  thread.id time.inclusive.duration 
              **0                     167** 
lhsx1         0                      50 
lhsx2         0                      59 
              **0                     159** 
lhsx1         0                      53 
lhsx2         0                      60

**Comment by twang15** [comment]
Thanks a lot!
I got the following report.
What are the marked lines (line 1 and 4)?

loop thread.id time.inclusive.duration
            **0              167**
lhsx1    0                 50
lhsx2    0                 59
             0                159
lhsx1    0                 53
lhsx2    0                 60

**Comment by twang15** [comment]
In my experiment, "add an annotation for the OpenMP thread ID" introduces very high overhead (more than 10X).

Is this expected or unexpected?
Can we just take records  for master thread? Would this help reduce overhead?

**Comment by daboehme** [comment]
I'd prefer taking the times on each thread as that will eventually allow you to compare times between threads. The `cali_set_int_byname()` call is not the most efficient way to set the thread ID, but a 10x overhead seems a bit much for the scenario above. Using `cali_set_int()` should be more efficient:

    cali_id_t thread_attr = 
        cali_create_attribute("thread.id", CALI_TYPE_INT, CALI_ATTR_ASVALUE | CALI_ATTR_SKIP_EVENTS);

    #pragma omp for
    for (...) {
        cali_set_int(thread_attr, omp_get_thread_num());
        
        CALI_MARK_LOOP_BEGIN(...)
        for(...) { loop1; }
        CALI_MARK_LOOP_END(...)

        CALI_MARK_LOOP_BEGIN(...)
        for(...) { loop2; }
        CALI_MARK_LOOP_END(...)
    }

If you *really* only want to annotate the sub-loops on the master thread, you'll have to put the annotations in a `omp master` region, and use the C API directly (the macros won't work in this way):

    cali_id_t loop_attr = 
         cali_find_attribute("loop");

    #pragma omp parallel for
    for (...) 
    {
    #pragma omp master
        {
            cali_begin_string(loop_attr, "loop1");
        }
    for (...);
    #pragma omp master
        {
            cali_end(loop_attr);
        }
    }

**Comment by twang15** [comment]
Thanks for the code examples.

Can we reduce the overhead by sampling only a small portion of loop
iterations, e.g., every 1 iteration in 100 iterations?

**Comment by daboehme** [comment]
Hi @twang15 ,

You can use any conditions you like around caliper annotation calls.

I'm still curious as to what caused the extremely high overhead when you added the OpenMP thread annotation. Did the second version (i.e., using `cali_set_int()` instead of `cali_set_int_byname()`) help? How much time do these loops usually take? If they are extremely short (less than ~20 microseconds) then the loop annotations do add significant overhead.

Caliper also has a sampling service; you can try using that instead of event tracing. This should have lower overhead. The following configuration sets up sampling with 100Hz and produces a sample trace:

    CALI_SERVICES_ENABLE=pthread:sampler:trace:recorder
    CALI_SAMPLER_FREQUENCY=100

To count the number of samples in each loop, you can then run 

    cali-query -t -s thread.id=0 -a count --aggregate-key loop

You can then multiply the count values by 100 to get the time in seconds.

**Comment by daboehme** [comment]
Closing this - questions have been answered, there are no further Caliper action items.
